services:
  matomo_loadgen:
    image: ghcr.io/puttrix/trafficinator:latest
    container_name: matomo-loadgen
    restart: unless-stopped
    environment:
      MATOMO_URL: "https://matomo.surputte.se/matomo.php"
      MATOMO_SITE_ID: "1"
      MATOMO_TOKEN_AUTH: "your_api_token_here"  # Replace with your actual Matomo API token
      URLS_FILE: /config/urls.txt
      TARGET_VISITS_PER_DAY: "20000"
      PAGEVIEWS_MIN: "3"
      PAGEVIEWS_MAX: "6"
      CONCURRENCY: "50"
      PAUSE_BETWEEN_PVS_MIN: "0.5"
      PAUSE_BETWEEN_PVS_MAX: "2.0"
      # Auto-stop options (choose one or both)
      AUTO_STOP_AFTER_HOURS: "0"       # stop after N hours (0 = disabled) — default disabled
      MAX_TOTAL_VISITS: "0"            # total visits before exit (0 = disabled)
      # Site search options
      SITESEARCH_PROBABILITY: "0.15"   # probability (0-1) that a visit includes site search
      # Visit duration options (in minutes)
      VISIT_DURATION_MIN: "1.0"        # minimum visit duration in minutes
      VISIT_DURATION_MAX: "8.0"        # maximum visit duration in minutes
      # Outlinks and downloads options
      OUTLINKS_PROBABILITY: "0.10"     # probability (0-1) that a visit includes outlinks
      DOWNLOADS_PROBABILITY: "0.08"    # probability (0-1) that a visit includes downloads
      # Custom events options
      CLICK_EVENTS_PROBABILITY: "0.25" # probability (0-1) that a visit includes click events
      RANDOM_EVENTS_PROBABILITY: "0.12" # probability (0-1) that a visit includes random events
      # Traffic sources options
      DIRECT_TRAFFIC_PROBABILITY: "0.30" # probability (0-1) for direct traffic (30% direct, 70% with referrers)
      # Geolocation options
      RANDOMIZE_VISITOR_COUNTRIES: "true" # enable realistic country distribution (true/false)
      # Ecommerce options
      ECOMMERCE_PROBABILITY: "0.05"       # probability (0-1) that a visit makes a purchase (5% = realistic)
      ECOMMERCE_ORDER_VALUE_MIN: "15.99"  # minimum order value
      ECOMMERCE_ORDER_VALUE_MAX: "299.99" # maximum order value  
      ECOMMERCE_ITEMS_MIN: "1"            # minimum items per order
      ECOMMERCE_ITEMS_MAX: "5"            # maximum items per order
      ECOMMERCE_TAX_RATE: "0.10"          # tax rate (10%)
      ECOMMERCE_SHIPPING_RATES: "0,5.99,9.99,15.99" # available shipping costs (comma-separated)
      ECOMMERCE_CURRENCY: "USD"           # currency code for ecommerce orders (ISO 4217)
      # Timezone options
      TIMEZONE: "UTC"                     # timezone for visit timestamps (e.g., "America/New_York", "Europe/Stockholm")
    # Config files are now embedded in the Docker image
    # volumes:
    #   - ./config:/config
    # If you front with Nginx Proxy Manager or a Cloudflare Tunnel container,
    # attach to that external network instead of publishing ports:
    # networks:
    #   - proxy

  # Scoped Watchtower: only monitors the "matomo-loadgen" container
  watchtower_trafficinator:
    image: containrrr/watchtower
    container_name: watchtower_trafficinator
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 matomo-loadgen
    # ↑ last arg = container name to watch

# networks:
#   proxy:
#     external: true