services:
  matomo_loadgen:
    build:
      context: ./matomo-load-baked
    container_name: matomo-loadgen
    restart: unless-stopped
    environment:
      MATOMO_URL: "https://matomo.surputte.se/matomo.php"
      MATOMO_SITE_ID: "1"
      URLS_FILE: /config/urls.txt
      TARGET_VISITS_PER_DAY: "20000"
      PAGEVIEWS_MIN: "3"
      PAGEVIEWS_MAX: "6"
      CONCURRENCY: "50"
      PAUSE_BETWEEN_PVS_MIN: "0.5"
      PAUSE_BETWEEN_PVS_MAX: "2.0"
      # Auto-stop options (choose one or both)
      AUTO_STOP_AFTER_HOURS: "0"       # stop after N hours (0 = disabled) — default disabled
      MAX_TOTAL_VISITS: "0"            # total visits before exit (0 = disabled)
      # Site search options
      SITESEARCH_PROBABILITY: "0.15"   # probability (0-1) that a visit includes site search
      # Visit duration options (in minutes)
      VISIT_DURATION_MIN: "1.0"        # minimum visit duration in minutes
      VISIT_DURATION_MAX: "8.0"        # maximum visit duration in minutes
      # Outlinks and downloads options
      OUTLINKS_PROBABILITY: "0.10"     # probability (0-1) that a visit includes outlinks
      DOWNLOADS_PROBABILITY: "0.08"    # probability (0-1) that a visit includes downloads
    volumes:
      - ./config:/config

